import Fastify, { type FastifyInstance } from 'fastify';
import cors from '@fastify/cors';
import cookie from '@fastify/cookie';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import multipart from '@fastify/multipart';
import { randomUUID } from 'node:crypto';
import { type Env, loadEnv } from './config/env.js';
import { errorHandler } from './shared/errors/error-handler.js';
import healthPlugin from './shared/plugins/health.js';
import { apiRateLimitPlugin } from './shared/plugins/rate-limit.js';
import authPlugin from './modules/auth/auth.plugin.js';
import activitiesPlugin from './modules/activities/activities.plugin.js';
import reviewsPlugin from './modules/reviews/reviews.plugin.js';
import boardsPlugin from './modules/boards/boards.plugin.js';
import supportEntriesPlugin from './modules/support-entries/support-entries.plugin.js';
import syncPlugin from './modules/sync/sync.plugin.js';
import { attachmentDownloadRoutes } from './modules/activities/attachments.routes.js';

export interface AppOptions {
  envOverrides?: Partial<Env>;
}

declare module 'fastify' {
  interface FastifyInstance {
    env: Env;
  }
}

export async function buildApp(options?: AppOptions): Promise<FastifyInstance> {
  const env: Env = {
    ...loadEnv(),
    ...options?.envOverrides,
  };

  const loggerConfig =
    env.NODE_ENV === 'test'
      ? { level: 'fatal' as const }
      : env.NODE_ENV === 'production'
        ? { level: env.LOG_LEVEL }
        : { level: env.LOG_LEVEL, transport: { target: 'pino-pretty', options: { translateTime: 'HH:MM:ss Z' } } };

  const app = Fastify({
    logger: loggerConfig,
    genReqId: () => randomUUID(),
  });

  // Decorate with env config so plugins can access it
  app.decorate('env', env);

  // ─── Middleware Pipeline ───────────────────────────────────────────────────
  // Order: request-id → logger → rate-limiter → CORS → security headers → auth → routes
  //
  // 1. Request-ID: Generated by Fastify via genReqId (above), enriched in onRequest hook
  // 2. Logger: Pino structured logging configured at instance creation
  // 3. Rate-limiter: Auth-scoped (inside auth plugin), API-scoped (global for domain routes)
  // 4. CORS: Origin validation and preflight handling
  // 5. Security headers: Added via onSend hook
  // 6. Auth: Applied per-route via preHandler in domain plugins
  // ──────────────────────────────────────────────────────────────────────────

  // 1. Request-id middleware: attach request ID to logger context for correlation
  app.addHook('onRequest', async (request) => {
    request.log = request.log.child({ requestId: request.id });
  });

  // 3. Global API rate limiter for authenticated domain routes (per userId, 100 req/min)
  await app.register(apiRateLimitPlugin);

  // Cookie parser (required for httpOnly refresh token cookies)
  await app.register(cookie);

  // 4. CORS
  await app.register(cors, {
    origin: env.CORS_ORIGINS,
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization', 'If-Match', 'If-Modified-Since'],
    exposedHeaders: ['ETag', 'X-RateLimit-Limit', 'X-RateLimit-Remaining', 'X-RateLimit-Reset', 'Retry-After'],
    credentials: true,
  });

  // 5. Security headers
  app.addHook('onSend', async (_request, reply, payload) => {
    reply.header('X-Content-Type-Options', 'nosniff');
    reply.header('X-Frame-Options', 'DENY');
    reply.header('Referrer-Policy', 'strict-origin-when-cross-origin');
    reply.header('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
    reply.header('X-Permitted-Cross-Domain-Policies', 'none');
    reply.header(
      'Content-Security-Policy',
      "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; connect-src 'self'; frame-ancestors 'none'"
    );
    if (env.NODE_ENV === 'production') {
      reply.header('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
    }
    return payload;
  });

  // Register multipart file upload support
  await app.register(multipart, {
    limits: {
      fileSize: env.UPLOAD_MAX_SIZE_MB * 1024 * 1024,
    },
  });

  // OpenAPI/Swagger documentation
  await app.register(swagger, {
    openapi: {
      info: {
        title: 'Workspace API',
        version: '1.0.0',
        description: 'Backend API for the Workspace personal productivity application',
      },
      servers: [{ url: `http://localhost:${env.PORT}` }],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
    },
  });

  if (env.NODE_ENV !== 'production') {
    await app.register(swaggerUi, {
      routePrefix: '/api/docs',
      uiConfig: { docExpansion: 'list' },
    });
  }

  // Global error handler
  app.setErrorHandler(errorHandler);

  // ─── Routes ────────────────────────────────────────────────────────────────

  // Health check and readiness endpoints (root level, no auth required)
  await app.register(healthPlugin);

  // Auth routes (registration, login, refresh, logout) — has its own scoped rate limiter
  await app.register(authPlugin, { prefix: '/api/v1/auth' });

  // Activities routes (CRUD, toggle completion, attachments)
  await app.register(activitiesPlugin);

  // Attachment download route (GET /api/v1/attachments/:id/download)
  await app.register(attachmentDownloadRoutes, { prefix: '/api/v1/attachments' });

  // Support entries routes (CRUD, formatted text, clear, attachments)
  await app.register(supportEntriesPlugin);

  // Boards routes (CRUD boards, items, position/size, batch)
  await app.register(boardsPlugin);

  // Reviews routes (create, update, unlock, history, list)
  await app.register(reviewsPlugin);

  // Sync routes (import localStorage data, push offline operations)
  await app.register(syncPlugin);

  return app;
}
